{"name": "test_login_with_valid_credentials[None-None]", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not iterable", "trace": "self = <tests.test_login.Test_login object at 0x109005a90>, email_address = None, password = None\n\n    @pytest.mark.parametrize(\"email_address,password\",\n                             ExcelUtilities.get_data_from_excel(\"Excelfiles/data_driven.xlsx\", \"Sheet1\"))\n    def test_login_with_valid_credentials(self, email_address, password):\n        home_page = Homepage(self.driver)\n        home_page.click_on_my_account()\n        login_page = home_page.select_login()\n>       login_page.enter_email_address(email_address)\n\ntests/test_login.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPages/LoginPage.py:20: in enter_email_address\n    self.type_into_element(email_add, \"email_address_xpath\", self.email_address_xpath)\nPages/BasePage.py:13: in type_into_element\n    element.send_keys(text)\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py:232: in send_keys\n    Command.SEND_KEYS_TO_ELEMENT, {\"text\": \"\".join(keys_to_typing(value)), \"value\": keys_to_typing(value)}\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nvalue = (None,)\n\n    def keys_to_typing(value: Iterable[AnyKey]) -> List[str]:\n        \"\"\"Processes the values that will be typed in the element.\"\"\"\n        characters: List[str] = []\n        for val in value:\n            if isinstance(val, Keys):\n                # Todo: Does this even work?\n                characters.append(val)\n            elif isinstance(val, (int, float)):\n                characters.extend(str(val))\n            else:\n>               characters.extend(val)\nE               TypeError: 'NoneType' object is not iterable\n\nvenv/lib/python3.12/site-packages/selenium/webdriver/common/utils.py:137: TypeError"}, "attachments": [{"name": "stdout", "source": "3169a582-d271-4bb9-9da3-32a40af5ef60-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "email_address", "value": "None"}, {"name": "password", "value": "None"}], "start": 1703240368158, "stop": 1703240369549, "uuid": "55f2dd37-5935-4a6d-9a91-a780713b95d2", "historyId": "17bad6b365ad31667be30d398f8b3651", "testCaseId": "d4f35a879d7330a6503c1c4e9b85123b", "fullName": "tests.test_login.Test_login#test_login_with_valid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "192.168.1.15"}, {"name": "thread", "value": "8581-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}