[32mINFO    [0m conftest:conftest.py:81 Starting a new test.
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50
[32mINFO    [0m conftest:test_workflow.py:32 Created order with ID: axE4qRzMNvhIjgERsQgg6
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "PATCH /orders/axE4qRzMNvhIjgERsQgg6 HTTP/11" 204 0
[32mINFO    [0m conftest:test_workflow.py:37 Updated order with ID: axE4qRzMNvhIjgERsQgg6
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "GET /orders/axE4qRzMNvhIjgERsQgg6 HTTP/11" 200 200
[32mINFO    [0m conftest:test_workflow.py:44 Retrieved updated order: {'id': 'axE4qRzMNvhIjgERsQgg6', 'bookId': 1, 'customerName': 'automation user updated', 'createdBy': '6da547055d4296961bf1a522bbac681e5431762b32b5b0db441c62fc35843530', 'quantity': 1, 'timestamp': 1726891834386}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "DELETE /orders/axE4qRzMNvhIjgERsQgg6 HTTP/11" 204 0
[32mINFO    [0m conftest:test_workflow.py:49 Deleted order with ID: axE4qRzMNvhIjgERsQgg6
[32mINFO    [0m conftest:conftest.py:83 Finished the test.